version: 2
registries:
  modb-test:
    type: maven-repository
    url: https://maven.pkg.github.com/manami-project/modb-test
    username: manami-project
    password: ${{secrets.PACKAGES_READ_TOKEN}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - modb-test
    schedule:
      interval: "daily"
